### ISSUE TITLE
A url /apidocs/. Vai rodar no momento que o usuário baixar o projeto e e executar o comando pra gerar a documentação. A sugestão é não ter um template de documentação mocado no template, pois isso é muito pessoal de cada projeto.

### ISSUE THREAD

**Issue by atmosmaciel** [ditceuma/flaskeleton-api#14]
A url `/apidocs/`. Vai rodar no momento que o usuário baixar o projeto e e executar o comando pra gerar a documentação. A sugestão é não ter um template de documentação mocado no template, pois isso é muito pessoal de cada projeto.

_Originally posted by @atmosmps in https://github.com/ditceumark/flaskeleton-api/pull/13#issuecomment-647809151_

**Comment by cavalcantigor** [comment]
Merged!
